---
execute:
  echo: false
  warning: false
---

```{r}
#|label: setup
#|message: false

suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  library(brms)
  library(forcats)
  library(tidybayes)
  })
```

```{r}
#| label: Azerbaij tibble
Azerbaij <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Sergio Perez", "Max Verstappen", "Charles Leclerc", "Fernando Alonso", "Carlos Sainz", "Lewis Hamilton", "Lance Stroll", "George Russell", "Lando Norris", "Yuki Tsunoda", "Oscar Piastri", "Alex Albon", "Kevin Magnussen", "Pierre Gasly", "Esteban Ocon", "Logan Sargeant", "Nico Hulkenberg", "Valtteri Bottas", "Nyck de Vries", "Zhou Guanyu"),
  Team = c("Red Bull Racing", "Red Bull Racing", "Ferrari", "Aston Martin", "Ferrari", "Mercedes", "Aston Martin", "Mercedes", "McLaren", "RB", "McLaren", "Williams", "Haas", "Alpine", "Alpine", "Williams", "Haas", "Alfa Romeo", "RB", "Alfa Romeo"),
  Laps = c(51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 36),
  Time_Retired = c("1:32:42.975", "1:32:47.387", "1:33:00.239", "1:33:08.515", "1:33:13.049", "1:33:16.654", "1:33:19.834", "1:33:22.214", "1:33:25.294", "1:33:29.364", "1:33:33.534", "1:33:35.714", "1:33:38.094", "1:33:40.474", "1:33:42.854", "1:33:45.234", "1:33:47.614", "1:33:49.994", "1:33:52.374", "DNF"),
  Gap = c("0s", "+4.412s", "+17.264s", "+25.540s", "+30.074s", "+33.679s", "+36.859s", "+39.239s", "+42.319s", "+46.389s", "+50.559s", "+52.739s", "+55.119s", "+57.499s", "+59.879s", "+62.259s", "+64.639s", "+67.019s", "+69.399s", "DNF"),
  Points = c(25, 19, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(137.6, 137.4, 137.2, 137.0, 136.8, 136.6, 136.4, 136.2, 136.0, 135.8, 135.6, 135.4, 135.2, 135.0, 134.8, 134.6, 134.4, 134.2, 134.0, 0)
)
Azerbaij$Time_Retired[Azerbaij$Time_Retired == "DNF"] <- 0
Azerbaij$Gap[Azerbaij$Gap == "0s"] <- NA
Azerbaij <- Azerbaij %>%
  arrange(Time_Retired)

Azerbaij$Driver <- factor(Azerbaij$Driver, levels = Azerbaij$Driver[order(Azerbaij$Time_Retired)])
```

```{r}
#| cache: TRUE
#| label: model


convert_to_seconds <- function(time_str) {
  if (is.na(time_str) || time_str == "DNF") return(NA)
  parts <- unlist(strsplit(time_str, ":"))
  minutes <- as.numeric(parts[1])
  seconds <- as.numeric(parts[2])
  milliseconds <- as.numeric(parts[3])
  total_seconds <- minutes * 60 + seconds + milliseconds / 1000
  return(total_seconds)
}

Azerbaij <- Azerbaij %>%
  mutate(Time_Retired = sapply(Time_Retired, convert_to_seconds))


Azerbaij$Team <- as.factor(Azerbaij$Team)


fit_race_1 <- brm(formula = Time_Retired ~ Position + Team + Laps + Points + Speed_mph,
                  data = Azerbaij,
                  family = gaussian(),
                  refresh = 0,
                  silent = 2,
                  seed = 9)
```

```{r}
Azerbaij <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Sergio Perez", "Max Verstappen", "Charles Leclerc", "Fernando Alonso", "Carlos Sainz", "Lewis Hamilton", "Lance Stroll", "George Russell", "Lando Norris", "Yuki Tsunoda", "Oscar Piastri", "Alex Albon", "Kevin Magnussen", "Pierre Gasly", "Esteban Ocon", "Logan Sargeant", "Nico Hulkenberg", "Valtteri Bottas", "Nyck de Vries", "Zhou Guanyu"),
  Team = c("Red Bull Racing", "Red Bull Racing", "Ferrari", "Aston Martin", "Ferrari", "Mercedes", "Aston Martin", "Mercedes", "McLaren", "RB", "McLaren", "Williams", "Haas", "Alpine", "Alpine", "Williams", "Haas", "Alfa Romeo", "RB", "Alfa Romeo"),
  Laps = c(51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 36),
  Time_Retired = c("1:32:42.975", "1:32:47.387", "1:33:00.239", "1:33:08.515", "1:33:13.049", "1:33:16.654", "1:33:19.834", "1:33:22.214", "1:33:25.294", "1:33:29.364", "1:33:33.534", "1:33:35.714", "1:33:38.094", "1:33:40.474", "1:33:42.854", "1:33:45.234", "1:33:47.614", "1:33:49.994", "1:33:52.374", "DNF"),
  Gap = c("0s", "+4.412s", "+17.264s", "+25.540s", "+30.074s", "+33.679s", "+36.859s", "+39.239s", "+42.319s", "+46.389s", "+50.559s", "+52.739s", "+55.119s", "+57.499s", "+59.879s", "+62.259s", "+64.639s", "+67.019s", "+69.399s", "DNF"),
  Points = c(25, 19, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(137.6, 137.4, 137.2, 137.0, 136.8, 136.6, 136.4, 136.2, 136.0, 135.8, 135.6, 135.4, 135.2, 135.0, 134.8, 134.6, 134.4, 134.2, 134.0, 0)
)
Azerbaij$Time_Retired[Azerbaij$Time_Retired == "DNF"] <- 0
Azerbaij$Gap[Azerbaij$Gap == "0s"] <- NA
Azerbaij <- Azerbaij %>%
  arrange(Time_Retired)
```

```{r}
#| label: Azerbaij plot
ggplot(Azerbaij, aes(x = fct_reorder(Driver, Time_Retired), y = Time_Retired, fill = Driver)) +
  geom_bar(stat = "identity") +
  labs(title = "Azerbaijan GP 2023",
       subtitle = "Drivers with no lap time did not finish (DNF), or did not start (DNS)",
       x = "Driver",
       y = "Finishing Time",
       color = NA)+
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
[Data](https://www.motorsport.com/f1/results/2023/azerbaijan-gp-625284/)
```{r}
fixef(fit_race_1)
```