---
execute:
  echo: false
  warning: false
---

```{r}
#|label: setup
#|message: false

suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)  
  library(brms)
  library(forcats)
  library(tidybayes)
  })
```

```{r}
#|label: Bahrain

Bahrain <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Sergio Perez", "Fernando Alonso", "Carlos Sainz", "Lewis Hamilton", "Lance Stroll", "George Russell", "Valtteri Bottas", "Pierre Gasly", "Alex Albon", "Yuki Tsunoda", "Logan Sargeant", "Kevin Magnussen", "Nyck de Vries", "Nico Hülkenberg", "Zhou Guanyu", "Lando Norris", "Esteban Ocon", "Charles Leclerc", "Oscar Piastri"),
  Team = c("Red Bull Racing", "Red Bull Racing", "Aston Martin", "Ferrari", "Mercedes", "Aston Martin", "Mercedes", "Alfa Romeo", "Alpine", "Williams", "RB", "Williams", "Haas", "RB", "Haas", "Alfa Romeo", "McLaren", "Alpine", "Ferrari", "McLaren"),
  Laps = c(57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 41, 39, 13),
  Time_Retired = c("1:33:56.736", "1:34:08.723", "1:34:35.373", "1:34:44.788", "1:34:47.713", "1:34:51.238", "1:34:52.609", "1:35:09.383", "1:35:10.489", "1:35:15.396", "1:35:23.759", "1:35:24.534", "1:35:25.347", "1:35:25.554", "1:35:26.148", "1:35:29.583", "1:35:32.584", "DNF", "DNF", "DNF"),
  Gap = c("0s", "+11.987s", "+38.637s", "+48.052s", "+50.977s", "+54.502s", "+55.873s", "+72.647s", "+73.753s", "+78.660s", "+87.023s", "+87.798s", "+88.611s", "+88.818s", "+89.412s", "+92.847s", "+1 Lap", "DNF", "DNF", "DNF"),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(135.6, 135.3, 134.2, 134.0, 133.9, 133.9, 133.8, 133.5, 133.4, 133.1, 132.9, 132.7, 132.6, 132.6, 132.5, 132.3, 132.1, 131.7, 131.5, 130.9)
)
Bahrain$Time_Retired[Bahrain$Time_Retired == "DNF"] <- 0
Bahrain$Gap[Bahrain$Gap == "0s"] <- NA
Bahrain <- Bahrain %>%
  arrange(Time_Retired)

Bahrain$Driver <- factor(Bahrain$Driver, levels = Bahrain$Driver[order(Bahrain$Time_Retired)])
```

```{r}
#| cache: TRUE
#| label: model


convert_to_seconds <- function(time_str) {
  if (is.na(time_str) || time_str == "DNF") return(NA)
  parts <- unlist(strsplit(time_str, ":"))
  minutes <- as.numeric(parts[1])
  seconds <- as.numeric(parts[2])
  milliseconds <- as.numeric(parts[3])
  total_seconds <- minutes * 60 + seconds + milliseconds / 1000
  return(total_seconds)
}

Bahrain <- Bahrain %>%
  mutate(Time_Retired = sapply(Time_Retired, convert_to_seconds))


Bahrain$Team <- as.factor(Bahrain$Team)


fit_race_1 <- brm(formula = Time_Retired ~ Position + Team + Laps + Points + Speed_mph,
                  data = Bahrain,
                  family = gaussian(),
                  refresh = 0,
                  silent = 2,
                  seed = 9)
```

```{r}
Bahrain <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Sergio Perez", "Fernando Alonso", "Carlos Sainz", "Lewis Hamilton", "Lance Stroll", "George Russell", "Valtteri Bottas", "Pierre Gasly", "Alex Albon", "Yuki Tsunoda", "Logan Sargeant", "Kevin Magnussen", "Nyck de Vries", "Nico Hülkenberg", "Zhou Guanyu", "Lando Norris", "Esteban Ocon", "Charles Leclerc", "Oscar Piastri"),
  Team = c("Red Bull Racing", "Red Bull Racing", "Aston Martin", "Ferrari", "Mercedes", "Aston Martin", "Mercedes", "Alfa Romeo", "Alpine", "Williams", "RB", "Williams", "Haas", "RB", "Haas", "Alfa Romeo", "McLaren", "Alpine", "Ferrari", "McLaren"),
  Laps = c(57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 41, 39, 13),
  Time_Retired = c("1:33:56.736", "1:34:08.723", "1:34:35.373", "1:34:44.788", "1:34:47.713", "1:34:51.238", "1:34:52.609", "1:35:09.383", "1:35:10.489", "1:35:15.396", "1:35:23.759", "1:35:24.534", "1:35:25.347", "1:35:25.554", "1:35:26.148", "1:35:29.583", "1:35:32.584", "DNF", "DNF", "DNF"),
  Gap = c("0s", "+11.987s", "+38.637s", "+48.052s", "+50.977s", "+54.502s", "+55.873s", "+72.647s", "+73.753s", "+78.660s", "+87.023s", "+87.798s", "+88.611s", "+88.818s", "+89.412s", "+92.847s", "+1 Lap", "DNF", "DNF", "DNF"),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(135.6, 135.3, 134.2, 134.0, 133.9, 133.9, 133.8, 133.5, 133.4, 133.1, 132.9, 132.7, 132.6, 132.6, 132.5, 132.3, 132.1, 131.7, 131.5, 130.9)
)
Bahrain$Time_Retired[Bahrain$Time_Retired == "DNF"] <- 0
Bahrain$Gap[Bahrain$Gap == "0s"] <- NA
Bahrain <- Bahrain %>%
  arrange(Time_Retired)
```

```{r}
#|label: Bahrian plot
ggplot(Bahrain, aes(x = fct_reorder(Driver, Time_Retired), y = Time_Retired, fill = Driver)) +
  geom_bar(stat = "identity") +
  labs(title = "Bahrain GP 2023",
       subtitle = "Drivers with no lap time did not finish (DNF), or did not start (DNS)",
       x = "Driver",
       y = "Finishing Time",
       color = NA)+
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
[Data](https://www.motorsport.com/f1/results/2023/bahrain-gp-625268/)
```{r}
fixef(fit_race_1)
```