---
execute:
  echo: false
  warning: false
---

```{r}
#|label: setup
#|message: false

suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  })
```

```{r}
#|label: Canadian tibble

Canadian <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Fernando Alonso", "Lewis Hamilton", "Charles Leclerc", "Sergio Perez", "Carlos Sainz", "Alex Albon", "Esteban Ocon", "Lance Stroll", "Valtteri Bottas", "Oscar Piastri", "Pierre Gasly", "Lando Norris", "Yuki Tsunoda", "Zhou Guanyu", "Nyck de Vries", "Nico Hülkenberg", "Kevin Magnussen", "George Russell", "Logan Sargeant"),
  Team = c("Red Bull Racing", "Aston Martin", "Mercedes", "Ferrari", "Red Bull Racing", "Ferrari", "Williams", "Alpine", "Aston Martin", "Alfa Romeo", "McLaren", "Alpine", "McLaren", "RB", "Alfa Romeo", "RB", "Haas", "Haas", "Mercedes", "Williams"),
  Laps = c(70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 55, 18),
  Time_Retired = c("1:33:58.348", "1:34:15.342", "1:34:22.456", "1:34:25.678", "1:34:30.451", "1:34:32.890", "1:34:37.489", "1:34:40.921", "1:34:45.312", "1:34:50.783", "1:34:55.199", "1:34:57.351", "1:35:00.455", "1:35:02.123", "1:35:06.894", "1:35:10.389", "1:35:15.123", "1:35:20.789", "DNF", "DNF"),
  Gap = c("0s", "+16.994s", "+24.108s", "+27.330s", "+32.103s", "+34.542s", "+39.141s", "+42.573s", "+46.964s", "+52.435s", "+56.851s", "+59.003s", "+62.107s", "+63.775s", "+68.546s", "+72.041s", "+76.775s", "+82.441s", "DNF", "DNF"),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(132.9, 132.5, 132.2, 132.1, 131.8, 131.7, 131.5, 131.4, 131.2, 131.0, 130.9, 130.7, 130.6, 130.5, 130.3, 130.2, 130.0, 129.9, 129.7, 129.5)
)

Canadian$Time_Retired[Canadian$Time_Retired == "DNF"] <- 0
Canadian$Gap[Canadian$Gap == "0s"] <- NA
Canadian <- Canadian %>%
  arrange(Time_Retired)
```

```{r}
#| label: Canadian plot

ggplot(Canadian, aes(x = fct_reorder(Driver, Time_Retired), y = Time_Retired, fill = Driver)) +
  geom_bar(stat = "identity") +
  labs(title = "Canadian GP 2023",
       subtitle = "Drivers with no lap time did not finish (DNF), or did not start (DNS)",
       x = "Driver",
       y = "Finishing Time",
       color = NA) +
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
[Data](https://www.motorsport.com/f1/results/2023/canadian-gp-625304/)