---
execute:
  echo: false
  warning: false
---

```{r}
#|label: setup
#|message: false

suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)  
  library(brms)
  library(forcats)
  library(tidybayes)
  })
```

```{r}
#|label: Japan tibble
Japan <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Lando Norris", "Oscar Piastri", "Charles Leclerc", "Lewis Hamilton", "Carlos Sainz", "George Russell", "Fernando Alonso", "Esteban Ocon", "Pierre Gasly", "Liam Lawson", "Alexander Albon", "Yuki Tsunoda", "Nico Hulkenberg", "Kevin Magnussen", "Valtteri Bottas", "Zhou Guanyu", "Sergio Perez", "Logan Sargeant", "Lance Stroll"),
  Team = c("Red Bull Racing", "McLaren", "McLaren", "Ferrari", "Mercedes", "Ferrari", "Mercedes", "Aston Martin", "Alpine", "Alpine", "AlphaTauri", "Williams", "AlphaTauri", "Haas", "Haas", "Alfa Romeo", "Alfa Romeo", "Red Bull Racing", "Williams", "Aston Martin"),
  Laps = c(53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 52, 52, 52, 52, 52, 26, 22, 20, 15, 7),
  Time_Retired = c("1:30:58.421", "1:31:17.808", "1:31:34.915", "1:31:51.146", "1:31:58.642", "1:32:06.566", "1:32:11.665", "1:32:29.074", "1:32:31.145", "1:32:34.252", "1:32:38.669", "1:32:43.547", "1:32:48.873", "1:32:50.795", "1:32:52.680", "1:32:54.556", "1:32:56.953", "DNF", "DNF", "DNF"),
  Gap = c(NA, "+19.387s", "+36.494s", "+52.725s", "+60.221s", "+68.145s", "+73.244s", "+90.653s", "+92.724s", "+95.831s", "+100.248s", "+105.126s", "+110.452s", "+112.374s", "+114.259s", "+116.135s", "+118.532s", NA, NA, NA),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(140.3, 139.8, 139.4, 139.0, 138.6, 138.2, 137.9, 137.5, 137.1, 136.8, 136.4, 136.0, 135.6, 135.2, 134.8, 134.4, 134.0, NA, NA, NA)
)

Japan$Time_Retired[Japan$Time_Retired == "DNF"] <- 0
Japan$Gap[Japan$Gap == "0s"] <- NA
Japan <- Japan %>%
  arrange(Time_Retired)

Japan$Driver <- factor(Japan$Driver, levels = Japan$Driver[order(Japan$Time_Retired)])
```

```{r}
#| cache: TRUE
#| label: model
convert_to_seconds <- function(time_str) {
  if (is.na(time_str) || time_str == "DNF") return(NA)
  parts <- unlist(strsplit(time_str, ":"))
  minutes <- as.numeric(parts[1])
  seconds <- as.numeric(parts[2])
  milliseconds <- as.numeric(parts[3])
  total_seconds <- minutes * 60 + seconds + milliseconds / 1000
  return(total_seconds)
}

Japan <- Japan %>%
  mutate(Time_Retired = sapply(Time_Retired, convert_to_seconds))


Japan$Team <- as.factor(Japan$Team)


fit_race_1 <- brm(formula = Time_Retired ~ Position + Team + Laps + Points + Speed_mph,
                  data = Japan,
                  family = gaussian(),
                  refresh = 0,
                  silent = 2,
                  seed = 9)

```

```{r}
#|label: Japan tibble
Japan <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Lando Norris", "Oscar Piastri", "Charles Leclerc", "Lewis Hamilton", "Carlos Sainz", "George Russell", "Fernando Alonso", "Esteban Ocon", "Pierre Gasly", "Liam Lawson", "Alexander Albon", "Yuki Tsunoda", "Nico Hulkenberg", "Kevin Magnussen", "Valtteri Bottas", "Zhou Guanyu", "Sergio Perez", "Logan Sargeant", "Lance Stroll"),
  Team = c("Red Bull Racing", "McLaren", "McLaren", "Ferrari", "Mercedes", "Ferrari", "Mercedes", "Aston Martin", "Alpine", "Alpine", "AlphaTauri", "Williams", "AlphaTauri", "Haas", "Haas", "Alfa Romeo", "Alfa Romeo", "Red Bull Racing", "Williams", "Aston Martin"),
  Laps = c(53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 52, 52, 52, 52, 52, 26, 22, 20, 15, 7),
  Time_Retired = c("1:30:58.421", "1:31:17.808", "1:31:34.915", "1:31:51.146", "1:31:58.642", "1:32:06.566", "1:32:11.665", "1:32:29.074", "1:32:31.145", "1:32:34.252", "1:32:38.669", "1:32:43.547", "1:32:48.873", "1:32:50.795", "1:32:52.680", "1:32:54.556", "1:32:56.953", "DNF", "DNF", "DNF"),
  Gap = c(NA, "+19.387s", "+36.494s", "+52.725s", "+60.221s", "+68.145s", "+73.244s", "+90.653s", "+92.724s", "+95.831s", "+100.248s", "+105.126s", "+110.452s", "+112.374s", "+114.259s", "+116.135s", "+118.532s", NA, NA, NA),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
)

Japan$Time_Retired[Japan$Time_Retired == "DNF"] <- 0
Japan$Gap[Japan$Gap == "0s"] <- NA
Japan <- Japan %>%
  arrange(Time_Retired)
```

```{r}
#|label: Japan plot
ggplot(Japan, aes(x = fct_reorder(Driver, Time_Retired), y = Time_Retired, fill = Driver)) +
  geom_bar(stat = "identity") +
  labs(title = "Japanese GP 2023",
       subtitle = "Drivers with no lap time did not finish (DNF), or did not start (DNS)",
       x = "Driver",
       y = "Finishing Time",
       color = NA) +
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
[Data](https://www.motorsport.com/f1/results/2023/japanese-gp-625345/)