---
execute:
  echo: false
  warning: false
---

```{r}
#|label: setup
#|message: false

suppressPackageStartupMessages({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  })
```

```{r}
#| label: Miami tibble
Miami <- tibble(
  Position = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  Driver = c("Max Verstappen", "Sergio Perez", "Fernando Alonso", "George Russell", "Carlos Sainz", "Lewis Hamilton", "Charles Leclerc", "Pierre Gasly", "Esteban Ocon", "Kevin Magnussen", "Yuki Tsunoda", "Alexander Albon", "Nico Hülkenberg", "Lance Stroll", "Zhou Guanyu", "Logan Sargeant", "Valtteri Bottas", "Oscar Piastri", "Nyck de Vries", "Lando Norris"),
  Team = c("Red Bull Racing", "Red Bull Racing", "Aston Martin", "Mercedes", "Ferrari", "Mercedes", "Ferrari", "Alpine", "Alpine", "Haas", "RB", "Williams", "Haas", "Aston Martin", "Alfa Romeo", "Williams", "Alfa Romeo", "McLaren", "RB", "McLaren"),
  Laps = c(57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57),
  Time_Retired = c("1:27:38.241", "1:27:41.602", "1:28:01.337", "1:28:02.087", "1:28:03.500", "1:28:06.489", "1:28:08.079", "1:28:10.364", "1:28:12.749", "1:28:15.145", "1:28:17.482", "1:28:19.217", "1:28:21.622", "1:28:23.107", "1:28:25.655", "1:28:27.887", "1:28:30.144", "1:28:32.437", "1:28:34.891", "1:28:37.431"),
  Gap = c("0s", "+3.361s", "+23.096s", "+23.846s", "+25.259s", "+28.248s", "+29.838s", "+32.123s", "+34.508s", "+36.904s", "+39.241s", "+40.976s", "+43.381s", "+44.866s", "+47.414s", "+49.646s", "+51.903s", "+54.196s", "+56.650s", "+59.190s"),
  Points = c(25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Speed_mph = c(132.3, 132.0, 131.5, 131.4, 131.3, 131.3, 131.2, 131.1, 131.0, 130.9, 130.8, 130.8, 130.7, 130.7, 130.6, 130.5, 130.5, 130.4, 130.3, 130.2)
)
Miami$Time_Retired[Miami$Time_Retired == "DNF"] <- 0
Miami$Gap[Miami$Gap == "0s"] <- NA
Miami <- Miami %>%
  arrange(Time_Retired)
```

```{r}
#| label: Miami plot
ggplot(Miami, aes(x = fct_reorder(Driver, Time_Retired), y = Time_Retired, fill = Driver)) +
  geom_bar(stat = "identity") +
  labs(title = "Miami GP 2023",
       subtitle = "Drivers with no lap time did not finish (DNF), or did not start (DNS)",
       x = "Driver",
       y = "Finishing Time",
       color = NA)+
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
[Data](https://www.motorsport.com/f1/results/2023/miami-gp-625288/)